// =============================
// scripts/map.js
// 
// Type this in the terminal: `node scripts/map.js`
// =============================

import fs from "fs";
import fsp from "fs/promises";
import path from "path";
import ignore from "ignore";

// ===== Settings =====
const outputMapPath = "PROJECT_STRUCTURE.md";
const IGNORE_EXT = [];
const EXCEPTION_NAMES = ["README.md", "robots.txt"];
const IGNORE_HIDDEN_FILES = true;
const MAX_DEPTH = 5; // Limits how deep the printed tree goes (stats are still 100% accurate)
const EXTRACT_INLINE_DESCRIPTIONS = false; // Grabs the first comment line of a file

const MAP_DESCRIPTION = `# Project Context Map 

## Description
\`${outputMapPath}\`: A generated file that provides a visual representation of the project's directory structure. It is intended to help developers and contributors understand the organization of the project and locate files more easily. The map is generated by traversing the project directory and listing all files and folders, while respecting .gitignore rules and other specified ignore settings.

The map is useful for quickly identifying the layout of the project, understanding the relationships between different components, and navigating the codebase. It can also serve as a reference for new contributors to get acquainted with the project's structure.`;

// Binary extensions – never read for LOC counting
const BINARY_EXTENSIONS = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico",
  ".mp4", ".webm", ".avi", ".mov", ".mp3", ".wav",
  ".pdf", ".zip", ".tar", ".gz", ".rar", ".7z",
  ".exe", ".dll", ".so", ".dylib", ".bin", ".dat",
  ".db", ".sqlite", ".ttf", ".woff", ".woff2", ".eot", ".otf",
  ".svg"
]);

// Lockfiles – skip LOC counting but keep in tree
const LOCKFILES = new Set([
  "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "composer.lock"
]);

// ===== Determine paths =====
const scriptDir = import.meta.dirname;
const rootDir = path.resolve(scriptDir, "../");
const outputFile = path.join(rootDir, outputMapPath);

// ===== Helpers =====
function formatSize(bytes) {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

// ===== Main Logic =====
async function generateContextMap() {
  const outputDir = path.dirname(outputFile);
  if (!fs.existsSync(outputDir)) await fsp.mkdir(outputDir, { recursive: true });

  // 1. Initialize Ignore Rules
  const ig = ignore().add('.git');
  try {
    const gitignoreContent = await fsp.readFile(path.join(rootDir, ".gitignore"), "utf-8");
    ig.add(gitignoreContent);
  } catch (err) {
    // No .gitignore found, proceed with defaults
  }

  // 2. Global State for Stats
  const stats = {
    totalFiles: 0,
    totalLoc: 0,
    totalSize: 0,
    extensions: {}, // ext -> { count, loc, size }
    topLevelDirs: {}, // dirName -> loc
    allCodeFiles: [] // { path, loc }
  };

  // 3. Asynchronous Recursive Traversal
  async function walk(currentPath, relPath) {
    const node = {
      name: relPath === '' ? path.basename(rootDir) : path.basename(currentPath),
      isDir: true,
      children: [],
      loc: 0,
      size: 0,
      isEmpty: false
    };

    let items;
    try {
      items = await fsp.readdir(currentPath, { withFileTypes: true });
    } catch (e) {
      return node;
    }

    for (const item of items) {
      if (item.name === '.git') continue; // Hard skip git

      const itemRelPath = relPath ? `${relPath}/${item.name}` : item.name;
      const isException = EXCEPTION_NAMES.includes(item.name);

      if (!isException) {
        if (IGNORE_HIDDEN_FILES && item.name.startsWith('.')) continue;
        if (!item.isDirectory() && IGNORE_EXT.some((ext) => item.name.endsWith(ext))) continue;

        // Note: `ignore` package expects trailing slashes for directories
        const ignoreCheckPath = item.isDirectory() ? itemRelPath + '/' : itemRelPath;
        if (ig.ignores(ignoreCheckPath)) continue;
      }

      const fullPath = path.join(currentPath, item.name);

      if (item.isDirectory()) {
        const childDirNode = await walk(fullPath, itemRelPath);
        node.children.push(childDirNode);
        node.loc += childDirNode.loc;
        node.size += childDirNode.size;
      } else {
        // File Processing
        stats.totalFiles++;
        const stat = await fsp.stat(fullPath).catch(() => ({ size: 0 }));
        const ext = path.extname(item.name).toLowerCase() || "(no extension)";
        let loc = 0;
        let description = null;

        if (!stats.extensions[ext]) {
          stats.extensions[ext] = { count: 0, loc: 0, size: 0 };
        }
        stats.extensions[ext].count++;
        stats.extensions[ext].size += stat.size;
        stats.totalSize += stat.size;

        const isBinary = BINARY_EXTENSIONS.has(ext);
        const isLockfile = LOCKFILES.has(item.name);

        if (!isBinary && !isLockfile) {
          try {
            const content = await fsp.readFile(fullPath, "utf-8");
            const lines = content.split('\n');
            loc = lines.length;
            stats.totalLoc += loc;

            // Extract Inline Description
            if (EXTRACT_INLINE_DESCRIPTIONS && lines.length > 0) {
              for (let i = 0; i < Math.min(10, lines.length); i++) {
                let line = lines[i].trim();
                // Match standard comment tokens: //, /*, or #
                if (line.match(/^[\/\*#]+/)) {
                  let text = line.replace(/^[\/\*#]+\s*/, '').trim();
                  text = text.replace(/\*\/$/, '').trim(); // Remove trailing */ if present

                  if (text.includes('=====') || text === '') continue;

                  const lowerText = text.toLowerCase();
                  if (lowerText.includes(item.name.toLowerCase()) || lowerText.includes(itemRelPath.toLowerCase())) {
                    continue; // Skip if it's just the file name/path
                  }

                  description = text;
                  break;
                } else if (line.length > 0) {
                  // Stop parsing if we hit real code
                  break;
                }
              }
            }
          } catch (e) {
            loc = 0;
          }

          stats.allCodeFiles.push({ path: itemRelPath, loc });

          // Attribute LOC to top-level directory
          const topLevel = itemRelPath.includes('/') ? itemRelPath.split('/')[0] : '(root)';
          stats.topLevelDirs[topLevel] = (stats.topLevelDirs[topLevel] || 0) + loc;
        }

        stats.extensions[ext].loc += loc;

        node.children.push({
          name: item.name,
          isDir: false,
          loc,
          size: stat.size,
          description
        });
        node.loc += loc;
        node.size += stat.size;
      }
    }

    // Sorting: Files/Folders based on depth
    node.children.sort((a, b) => {
      if (relPath !== '') {
        // Deep levels: Directories first
        if (a.isDir !== b.isDir) return b.isDir ? 1 : -1;
      } else {
        // Root level: Files first
        if (a.isDir !== b.isDir) return a.isDir ? 1 : -1;
      }
      return a.name.localeCompare(b.name);
    });

    node.isEmpty = node.children.length === 0;
    return node;
  }

  const rootNode = await walk(rootDir, "");

  // 4. Output Generation
  const outputStream = fs.createWriteStream(outputFile, { encoding: "utf-8" });

  if (MAP_DESCRIPTION && MAP_DESCRIPTION.trim()) {
    outputStream.write(`${MAP_DESCRIPTION.trim()}\n\n`);
  }

  outputStream.write("## Map of Project Structure\n\n");
  outputStream.write("```text\n");

  async function renderTree(node, prefix = "", isLast = true, isRoot = true, currentDepth = 0) {
    let line = "";
    const connector = isRoot ? "" : (isLast ? "└── " : "├── ");

    line += prefix + connector + node.name;
    if (node.isDir) line += "/";

    // Directory stats & flags
    if (node.isDir && !isRoot) {
      if (node.isEmpty) line += " (empty)";
      else line += ` [${formatSize(node.size)}, ${node.loc} LOC]`;
    }
    // File descriptions
    if (!node.isDir && node.description) {
      line += ` - ${node.description}`;
    }

    outputStream.write(line + "\n");

    if (node.isDir && currentDepth < MAX_DEPTH) {
      const newPrefix = isRoot ? "" : prefix + (isLast ? "    " : "│   ");
      for (let i = 0; i < node.children.length; i++) {
        const child = node.children[i];
        const childIsLast = i === node.children.length - 1;
        await renderTree(child, newPrefix, childIsLast, false, currentDepth + 1);

        // Blank line visual separator for directories
        if (child.isDir && !childIsLast) {
          outputStream.write(newPrefix + "│\n");
        }
      }
    } else if (node.isDir && currentDepth >= MAX_DEPTH && node.children.length > 0) {
      // Just visually indicate truncation
      const newPrefix = isRoot ? "" : prefix + (isLast ? "    " : "│   ");
      outputStream.write(newPrefix + "└── ... (max depth reached)\n");
    }
  }

  await renderTree(rootNode);
  outputStream.write("```\n\n");

  // 5. Build Analytical Summaries
  outputStream.write("## Codebase Summary\n\n");

  const codeExts = [];
  const binExts = [];

  for (const [ext, data] of Object.entries(stats.extensions)) {
    if (BINARY_EXTENSIONS.has(ext)) binExts.push([ext, data]);
    else codeExts.push([ext, data]);
  }

  // --- Directory-Level LOC ---
  const sortedDirs = Object.entries(stats.topLevelDirs).sort((a, b) => b[1] - a[1]);
  if (sortedDirs.length > 0) {
    outputStream.write("### Directory-Level LOC Breakdown\n\n");
    outputStream.write("| Directory | Lines of Code |\n");
    outputStream.write("|-----------|---------------|\n");
    for (const [dir, loc] of sortedDirs) {
      outputStream.write(`| \`${dir}\` | ${loc} |\n`);
    }
    outputStream.write("\n");
  }

  // --- Top 10 Largest Code Files ---
  const top10Files = stats.allCodeFiles.sort((a, b) => b.loc - a.loc).slice(0, 10);
  if (top10Files.length > 0) {
    outputStream.write("### Top 10 Largest Code Files\n\n");
    outputStream.write("| File | Lines of Code |\n");
    outputStream.write("|------|---------------|\n");
    for (const file of top10Files) {
      outputStream.write(`| \`${file.path}\` | ${file.loc} |\n`);
    }
    outputStream.write("\n");
  }

  // --- Code Files Table ---
  codeExts.sort((a, b) => b[1].count - a[1].count);
  if (codeExts.length > 0) {
    outputStream.write("### Code Files\n\n");
    outputStream.write("| Extension | Files | Lines of Code | Size |\n");
    outputStream.write("|-----------|-------|---------------|------------|\n");
    let codeFiles = 0;
    let codeSize = 0;
    for (const [ext, data] of codeExts) {
      outputStream.write(`| ${ext} | ${data.count} | ${data.loc} | ${formatSize(data.size)} |\n`);
      codeFiles += data.count;
      codeSize += data.size;
    }
    outputStream.write(`| **Total** | **${codeFiles}** | **${stats.totalLoc}** | **${formatSize(codeSize)}** |\n\n`);
  }

  // --- Binary Files Table ---
  binExts.sort((a, b) => b[1].count - a[1].count);
  if (binExts.length > 0) {
    outputStream.write("### Binary / Media Files (Physical Size)\n\n");
    outputStream.write("| Extension | Files | Size |\n");
    outputStream.write("|-----------|-------|------------|\n");
    let binFiles = 0;
    let binSize = 0;
    for (const [ext, data] of binExts) {
      outputStream.write(`| ${ext} | ${data.count} | ${formatSize(data.size)} |\n`);
      binFiles += data.count;
      binSize += data.size;
    }
    outputStream.write(`| **Total** | **${binFiles}** | **${formatSize(binSize)}** |\n\n`);
  }

  outputStream.write(`**Grand Total Files:** ${stats.totalFiles}  \n`);
  outputStream.write(`**Total Repository Size:** ${formatSize(stats.totalSize)}\n`);

  outputStream.end();

  const relativeOutput = path.relative(rootDir, outputFile);
  console.log(`Done! Check: ${relativeOutput}`);
}

generateContextMap();